  version: "3.8"

  services:
    backend:
      build:
        context: ./server
        dockerfile: Dockerfile.prod
      container_name: pp-backend
      env_file:
        - ./server/.env.production
      restart: always
      network_mode: host
      volumes:
        - /var/www/imas/multi_media:/var/www/imas/multi_media

    frontend:
      build:
        context: ./client
        dockerfile: Dockerfile.prod
      container_name: pp-portal-client
      restart: always
      ports:
        - "3000:80"
